---
- name: Check for EPEL repo
  stat:
    path: "/etc/yum.repos.d/epel.repo"
  register: epel

- name: EPEL repo key
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ansible_distribution_major_version}}

- name: Install EPEL repository (RHEL)
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm"
  when: not epel.stat.exists

