---
- name: Update package cache
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: apt update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
  when: ansible_os_family == 'Debian'
- name: Insert a line to the bottom of nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: include /etc/nginx/passthrough.conf;

- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: copy nginx passthrough.conf
  template:
    src: passthrough.conf.j2
    dest: /etc/nginx/passthrough.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx
