---
- name: Install createrepo
  yum:
    name: createrepo
    state: present

- name: Clean local repo
  file:
    path: "/xroad/"
    state: absent
  tags:
    - clean-local-repo

- name: Copy RPM packages (RHEL)
  copy:
    src: "../src/packages/build/rhel/{{ ansible_distribution_major_version }}/"
    dest: /xroad/

- name: Create local package repository (RHEL)
  command: createrepo /xroad/
